###############
# Build stage #
###############
FROM ubuntu AS builder

ENV DEBIAN_FRONTEND=noninteractive
ENV PATH=$PATH:/usr/local/go/bin

RUN apt update && apt upgrade -y &&\
    apt install -y git gcc g++ curl jq rsync &&\
    curl -L -s -o go1.22.7.linux-amd64.tar.gz https://go.dev/dl/go1.22.7.linux-amd64.tar.gz &&\
    rm -rf /usr/local/go && tar -C /usr/local -xvf go1.22.7.linux-amd64.tar.gz

WORKDIR /
RUN git clone https://github.com/flare-foundation/go-flare /flare &&\
    cd /flare/avalanchego &&\
    git switch --detach v0.6.6-songbird &&\
    ./scripts/build.sh

#################
# Cleanup stage #
#################
FROM ubuntu AS execution

ENV HOME="/flare"

RUN apt update &&\
    apt upgrade -y &&\
    apt install -y curl jq

COPY --from=builder /flare/avalanchego/build/ /flare/avalanchego/scripts /flare
COPY songbird.sh /flare/songbird.sh
RUN chmod +x /flare/songbird.sh

WORKDIR /flare
CMD ["/flare/songbird.sh"]