###############
# Build stage #
###############
FROM alpine AS builder

RUN apk update &&\
    apk upgrade &&\
    apk add --no-cache bash curl git go jq rsync

WORKDIR /
RUN git clone https://github.com/flare-foundation/go-flare /flare &&\
    cd /flare/avalanchego &&\
    git switch --detach v0.6.6-songbird &&\
    ./scripts/build.sh

#################
# Cleanup stage #
#################
FROM alpine AS execution

ENV PS1="\[\033[01;32m\]\u\[\033[01;34m\]@\[\033[01;32m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
ENV HOME="/flare"

RUN apk update &&\
    apk upgrade &&\
    apk add --no-cache bash curl jq

COPY --from=builder /flare/avalanchego/build/ /flare/avalanchego/scripts /flare
COPY songbird.sh /flare/songbird.sh
RUN chmod +x /flare/songbird.sh

WORKDIR /flare
CMD ["/flare/songbird.sh"]